services:
  api:
    build: .
    container_name: dballz-api
    ports:
      - "8080:8080"
    environment:
      - EXTERNAL_API_URL=https://dragonball-api.com/api
      - GIN_MODE=release
    restart: always
